#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo "usage: $0 <img>"
  exit 1
fi

retry() {
  for i in 1 2 3 4 5; do
    if eval "$@"; then
      return 0
    fi
    sleep 1s
  done
  return 1
}

set -xe

if SD_MUX=$(sd-mux-ctrl -v 0 --status); then
  if [[ "$SD_MUX" == "SD connected to: DUT" ]]; then
    sd-mux-ctrl -v 0 --ts
    sleep 1s
  fi
fi

DEVICES=( $(find /dev/disk/by-id/ -name 'usb-*' -not -name '*-part*') )

if [[ "${#DEVICES[@]}" -eq 0 ]]; then
  echo "No USB devices."
  exit 1
elif [[ "${#DEVICES[@]}" -ne 1 ]]; then
  echo "Many devices: ${DEVICES[@]}"
  exit 1
fi

DISK="${DEVICES[0]}"
echo "Using $DISK..."

zstd -d -c "$1" | pv | dd of="$DISK" bs=512k iflag=fullblock oflag=direct
sync
sd-mux-ctrl -v 0 --dut || true
