#!/bin/sh

LOCALPATH=$(pwd)
ROOTDIR=$(cd $(dirname $(dirname $0)); pwd)
BOARD=$1

if [ $# != 1 ] ; then 
BOARD=kylin
fi
${ROOTDIR}/build/mkuboot ${BOARD}
${ROOTDIR}/build/mkkernel ${BOARD} 
${ROOTDIR}/build/mkrootfs ${BOARD} 
