#!/bin/bash -e

LOCALPATH=$(pwd)
ROOTDIR=$(dirname $(dirname $(readlink -f $0)))
OUT=${ROOTDIR}/out
IMAGE=${ROOTDIR}/image
BOARD=$1
DEFCONFIG=""
DTB=""
KERNELIMAGE=""

finish() {
    echo -e "\e[31m MAKE KERNEL IMAGE FAILED.\e[0m"
    exit -1
}
trap finish ERR

if [ $# != 1 ] ; then
    BOARD=kylin
fi

KERNELIMAGE=${IMAGE}/${BOARD}-kernel.img

[ ! -d ${OUT} ] && mkdir ${OUT}
[ ! -d ${IMAGE} ] && mkdir ${IMAGE}

case ${BOARD} in
    "kylin")
        DEFCONFIG=rk3036_kylin_linux_defconfig
        DTB=rk3036-kylin.dtb
        ;;
    "firefly")
        DEFCONFIG=""
        DTB=rk3288-firefly.dtb
        ;;
    "rk3036evb")
        DEFCONFIG=""
        DTB=rk3036-evb.dtb
        ;;
    *)
        echo "board '${BOARD}' not supported!"
        return
        ;;
esac

echo Building kernel for ${BOARD} board!
echo Using ${DEFCONFIG}

cd ${ROOTDIR}/kernel
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- O=${OUT}/kernel ${DEFCONFIG}
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- O=${OUT}/kernel -j8
cat ${OUT}/kernel/arch/arm/boot/zImage ${OUT}/kernel/arch/arm/boot/dts/${DTB} > ${KERNELIMAGE}.zimage
mkimage -A arm -O linux -T kernel -C none -a 0x60800800 -d ${KERNELIMAGE}.zimage ${KERNELIMAGE}
rm ${KERNELIMAGE}.zimage
cd ${LOCALPATH}
echo Kernel uImage with dtb appended: ${KERNELIMAGE}
