#!/bin/bash

LOCALPATH=$(pwd)
ROOTDIR=$(cd $(dirname $(dirname $0)); pwd)
OUT=${ROOTDIR}/out
IMAGE=${ROOTDIR}/image
BOARD=$1
DEFCONFIG=""

if [ $# != 1 ] ; then 
BOARD=kylin
fi
OUTBIN=${BOARD}-uboot.bin


if [ ! -d ${OUT} ];then
mkdir ${OUT}
fi

if [ ! -d ${IMAGE} ];then
mkdir ${IMAGE}
fi

case ${BOARD} in
	"kylin")
		DEFCONFIG=kylin-rk3036_defconfig
	;;
	"firefly")
		DEFCONFIG=firefly-rk3288_defconfig
	;;
	"rk3036evb")
		DEFCONFIG=evb-rk3036_defconfig
	;;
	*)
	echo "board not support in U-boot"
	;;
esac


echo Building U-boot for ${BOARD} board!
echo Using ${DEFCONFIG}

cd ${ROOTDIR}/u-boot
CROSS_COMPILE=arm-linux-gnueabi- make O=../out/uboot ${DEFCONFIG} all
cd ${OUT}/uboot
tools/mkimage  -n rk3036 -T rksd -d spl/u-boot-spl.bin spl.bin
dd if=/dev/zero of=${IMAGE}/${OUTBIN} count=64
cat spl.bin u-boot-dtb.bin >> ${IMAGE}/${OUTBIN}
echo U-boot image:${IMAGE}/${OUTBIN}
cd ${LOCALPATH}
