#!/bin/bash

for i in $@; do
  if [[ "#(basename "$1")" != "$1" ]]; then
    echo "$1 has to be file name"
    exit 1
  fi
done

if [[ ! -d /sys/kernel/config/device-tree/overlays ]]; then
  echo "Your kernel does not support CONFIG_OF_OVERLAY."
  exit 1
fi

set -eo pipefail
cd /sys/kernel/config/device-tree/overlays

for i in $@; do
  rmdir $i || true
done
