#!/bin/bash

if [[ $# -lt 3 ]]; then
  echo "usage: $0 <name> <target-path> <okay|disabled> <additional dt configs...>"
  exit 1
fi

if [[ "$(basename "$1")" != "$1" ]]; then
  echo "$1: has to be file name"
  exit 1
fi

if [[ ! -d /sys/kernel/config/device-tree/overlays ]]; then
  echo "Your kernel does not support CONFIG_OF_OVERLAY."
  exit 1
fi

if ! which dtc &>/dev/null; then
  echo "Please install dtc: sudo apt-get install device-tree-compiler"
  exit 1
fi

if [[ "$3" != "okay" ]] && [[ "$3" != "disabled" ]]; then
  echo "$3: only 'okay' or 'disabled' is valid"
  exit 1
fi

NAME="$1"
TARGET="$2"
STATUS="$3"
shift 3

set -eo pipefail
cd /sys/kernel/config/device-tree/overlays

rmdir "$NAME" 2>/dev/null || true
mkdir -p "$NAME"

args() {
  for i in "$@"; do
    echo "$i;"
  done
}

generate() {
cat <<EOF
/dts-v1/;
/ {
	fragment@0 {
		target-path = "/$TARGET";
		__overlay__ {
			$(args status=\"$STATUS\" "$@")
		};
	};
};
EOF
}

echo "Applying..."
generate "$@"

generate "$@" | dtc -I dts -Odtb -o "$NAME/dtbo"

if [[ "$(cat "$NAME/status")" == "applied" ]]; then
  echo "Applied!"
else
  cat "$NAME/status"
  rmdir "$NAME"
fi
